### ISSUE TITLE
add neo4j 4.2 version

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-neo4j#7]

**Comment by zengxc-1996** [comment]
root@iZj6c4505znop1e5m2eoqiZ:/etc/apt/sources.list.d#
` cat neo4j.list` 
deb https://debian.neo4j.com stable 4.1
deb https://debian.neo4j.com stable 4.2
deb https://debian.neo4j.com stable 4.0
deb https://debian.neo4j.com stable 3.5
root@iZj6c4505znop1e5m2eoqiZ:/etc/apt/sources.list.d# 
`apt update`
`apt list |grep neo4j`
libneo4j-client-dev/bionic 2.2.0-1build1 amd64
libneo4j-client-doc/bionic,bionic 2.2.0-1build1 all
libneo4j-client11/bionic 2.2.0-1build1 amd64
neo4j/stable,stable 1:4.2.3 all
neo4j-client/bionic 2.2.0-1build1 amd64
neo4j-enterprise/stable,stable 1:4.2.3 all

There is no small version of ubunutu repo

**Comment by chendelin1982** [comment]
Verify these
* Is there Chinese language at Neo4j Browser?
* How to create new user of Neo4j?

**Comment by zengxc-1996** [comment]
neo4j4.1  After remaking images; 
 test OK
neo4j + auto password  can login
