### ISSUE TITLE
Neo4j4.2.3 can not log in on Ubuntu/AmazonLinux of AWS

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-neo4j#9]
Neo4j4.2.3 can not log in on Ubuntu/AmazonLinux of AWS

**Comment by chendelin1982** [comment]
`python3 build.py -t` and login is OK on AmazonLinux2, Neo4j version is 4.2.3
`python3 build.py -t` and login is OK on Ubuntu, Neo4j version is 4.2.3

**Comment by qiaofeng1227** [comment]
when init runing , neo4j is not starting.
Init excute after neo4j service.
Done
